GET http://laoliapi.cn/king/qc_yuyin.php?msg=test
Content-Type: application/json

###
GET https://api.imjad.cn/pixiv/v2/?type=search&word=崩坏3
Content-Type: application/json

###
GET https://api.few.gs/pixiv/illust/info/5171516
Content-Type: application/json

###
GET https://s0.xinger.ink/acgimg/acgurl.php
Content-Type: application/json

###